/**
 * @file        RASAeroImport.h
 * @authors     Ayberk Yaraneri
 *
 * @brief      A utility class used to parse aerodynamic coefficients and
 * parameters generated by the RASAero software. The class stores the aero
 * parameters into a lookup table and makes them readily available through
 * getter functions. These getters interpolate the data as necessary.
 *
 */

#ifndef _RASAERO_IMPORT_H_
#define _RASAERO_IMPORT_H_

#include <Eigen/Dense>
#include <string>
#include <vector>

class RASAeroImport {
   public:
    RASAeroImport(std::string file_path);

    /**************** Retrieve Aero Parameters of Rocket **********************/
    double get_Cp_location(double mach, double alpha,
                           double protuberance_percent);
    double get_CNa(double mach, double alpha, double protuberance_percent);
    double get_CA_poweroff(double mach, double alpha,
                           double protuberance_percent);
    double get_CA_poweron(double mach, double alpha,
                          double protuberance_percent);
    double get_CD_protuberance(double mach, double alpha,
                               double protuberance_percent);

    /************************ Set Parameters **********************************/
    void set_mach_number_instances();
    void set_alpha_instances();
    void set_protuberance_instances();
    void set_mach_number_fidelity();
    void set_alpha_fidelity();
    void set_protuberance_fidelity();

   private:

    // Some metadata useful for interpolation
    int mach_number_instances_;    // Number of mach numbers in the table
    double mach_number_fidelity_;  // Distance between mach numbers in table

    int alpha_instances_;    // Number of alpha values in the table
    double alpha_fidelity_;  // Distance between alpha values in table

    int protuberance_instances_;    // Number of protoberance values in table
    double protuberance_fidelity_;  // Distance between protub. values in table

    // Aero Parameter Lookup Table
    Eigen::MatrixXd aero_table_;
};

#endif
