/**
 * @file        RASAeroImport.cpp
 * @authors     Ayberk Yaraneri
 *
 * @brief      A utility class used to parse aerodynamic coefficients and
 * parameters generated by the RASAero software. The class stores the aero
 * parameters into a lookup table and makes them readily available through
 * getter functions. These getters interpolate the data as necessary.
 *
 */

#include "RASAeroImport.h"

#include <rapidcsv.h>

#include <string>

RASAeroImport::RASAeroImport(std::string file_path) {
    rapidcsv::Document csv(file_path);
}
